export const SupplementUnits = {
  "demir": { value: 30, unit: "mg" },
  "iron": { value: 30, unit: "mg" },
  "folik asit": { value: 400, unit: "mcg" },
  "folic acid": { value: 400, unit: "mcg" },
  "vitamin d": { value: 1000, unit: "IU" },
  "kalsiyum": { value: 500, unit: "mg" },
  "calcium": { value: 500, unit: "mg" },
  "omega 3": { value: 1000, unit: "mg" },
  "omega-3": { value: 1000, unit: "mg" },
  "protein": { value: 30, unit: "g" },
  "b12": { value: 2.4, unit: "mcg" },
  "vitamin b12": { value: 2.4, unit: "mcg" },
  "b12 vitamin": { value: 2.4, unit: "mcg" },
  "magnezyum": { value: 300, unit: "mg" },
  "magnesium": { value: 300, unit: "mg" },
  "çinko": { value: 10, unit: "mg" },
  "zinc": { value: 10, unit: "mg" },
};
